# Generated by Django 5.1.3 on 2024-11-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_ponto_fim_intervalo_ponto_inicio_intervalo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='fim_intervalo',
            new_name='intervalo_fim',
        ),
        migrations.RenameField(
            model_name='ponto',
            old_name='inicio_intervalo',
            new_name='intervalo_inicio',
        ),
    ]
