# Generated by Django 5.1.3 on 2024-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_rename_fim_intervalo_ponto_intervalo_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='intervalo_fim',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='intervalo_inicio',
        ),
        migrations.AddField(
            model_name='ponto',
            name='fim_intervalo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='inicio_intervalo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
