# Generated by Django 5.1.3 on 2024-11-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0006_alter_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='fim_intervalo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='inicio_intervalo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
